[package]
name = "pg-bart"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = { version = "0.15.6" }
numpy = { version = "0.21.0" }
rand = { version = "0.8.5" }
rand_distr = { version = "0.4.3" }
