name: Run tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    needs: [linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Download the artifact from your Linux x86_64 job (adjust if you need other arches)
      - name: Download Wheels
        uses: actions/download-artifact@v4
        with:
          name: linux-x86_64-wheels
          path: dist

      - name: Install Python & Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Optionally run your Rust tests here (or in the linux job itself)
      - name: Rust tests
        run: cargo test --all

      - name: Install wheel and Python test dependencies
        run: |
          pip install --force-reinstall --find-links dist 'pymc-bart-rs[all]'
          pip install pytest

      - name: Run Python tests
        run: pytest
